meta_product_name: "New in Town"
meta_title: "New in Town - Feel like a local"
meta_description: "Learn to navigate a new city browsing rapidly and easily though tips from locals. Help others avoid social awkwardness by voting what content helped you or even writing your own pro advice!"
meta_image: "cover.png" # should exist in `app/assets/images/`
